"""File Generated by Sideko (sideko.dev)"""

import io
import typing
import typing_extensions
from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class GetChatUsersUserIdChannelsChannelIdAdminsResponseAdminsItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    email: typing.Optional[str] = _PydanticField(alias="email", default=None)
    first_name: typing.Optional[str] = _PydanticField(alias="first_name", default=None)
    id: typing.Optional[str] = _PydanticField(alias="id", default=None)
    member_id: typing.Optional[str] = _PydanticField(alias="member_id", default=None)
    role: typing.Optional[typing_extensions.Literal["admin", "owner"]] = _PydanticField(
        alias="role", default=None
    )
    last_name: typing.Optional[str] = _PydanticField(alias="last_name", default=None)
    name: typing.Optional[str] = _PydanticField(alias="name", default=None)


class PostChatUsersUserIdChannelsChannelIdAdminsResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    added_at: typing.Optional[str] = _PydanticField(alias="added_at", default=None)
    ids: typing.Optional[str] = _PydanticField(alias="ids", default=None)
    member_ids: typing.Optional[str] = _PydanticField(alias="member_ids", default=None)


class GetChatUsersUserIdChannelsChannelIdAdminsResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    admins: typing.Optional[
        typing.List[GetChatUsersUserIdChannelsChannelIdAdminsResponseAdminsItem]
    ] = _PydanticField(alias="admins", default=None)
    next_page_token: typing.Optional[str] = _PydanticField(
        alias="next_page_token", default=None
    )
    page_size: typing.Optional[int] = _PydanticField(alias="page_size", default=None)
