"""File Generated by Sideko (sideko.dev)"""

import io
import typing
import typing_extensions
from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class GetChatSpacesSpaceIdChannelsResponseChannelsItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    channel_id: str = _PydanticField(alias="channel_id")
    channel_name: str = _PydanticField(alias="channel_name")
    description: typing.Optional[str] = _PydanticField(
        alias="description", default=None
    )
    space_channel_type: typing_extensions.Literal[
        "private", "public_for_members", "general"
    ] = _PydanticField(alias="space_channel_type")
    member_count: int = _PydanticField(alias="member_count")


class PatchChatSpacesSpaceIdChannelsResponseChannelsItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    channel_id: str = _PydanticField(alias="channel_id")
    is_moved: bool = _PydanticField(alias="is_moved")


class GetChatSpacesSpaceIdChannelsResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    next_page_token: typing.Optional[str] = _PydanticField(
        alias="next_page_token", default=None
    )
    page_size: typing.Optional[int] = _PydanticField(alias="page_size", default=None)
    channels: typing.List[GetChatSpacesSpaceIdChannelsResponseChannelsItem] = (
        _PydanticField(alias="channels")
    )


class PatchChatSpacesSpaceIdChannelsResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    space_id: str = _PydanticField(alias="space_id")
    move_direction: str = _PydanticField(alias="move_direction")
    channels: typing.List[PatchChatSpacesSpaceIdChannelsResponseChannelsItem] = (
        _PydanticField(alias="channels")
    )
