"""File Generated by Sideko (sideko.dev)"""

import pytest
from zoom_team_chat import AsyncClient, Client
from os import getenv
from zoom_team_chat.types.chat.space.admin import models
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_promote_201_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(token=getenv("API_TOKEN"))
    response = client.chat.space.admin.promote(
        space_id="8609fdea87b44e2f8e0",
        data={"members": [{"identifier": "1vRFhZt_2gipkB\-SFKkOpnkh"}]},
    )
    adapter = TypeAdapter(models.PostChatSpacesSpaceIdAdminsResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_promote_201_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(token=getenv("API_TOKEN"))
    response = await client.chat.space.admin.promote(
        space_id="8609fdea87b44e2f8e0",
        data={"members": [{"identifier": "1vRFhZt_2gipkB\-SFKkOpnkh"}]},
    )
    adapter = TypeAdapter(models.PostChatSpacesSpaceIdAdminsResponse)
    adapter.validate_python(response)


def test_demote_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(token=getenv("API_TOKEN"))
    response = client.chat.space.admin.demote(
        space_id="8609fdea87b44e2f8e0",
        identifiers="zqmgs2tmspguoqcxyahsya,R4VM29Oj0fVM2hhEmSKVM2hhezJTezJTKVM2hezJT2hezJ",
    )
    adapter = TypeAdapter(models.DeleteChatSpacesSpaceIdAdminsResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_demote_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(token=getenv("API_TOKEN"))
    response = await client.chat.space.admin.demote(
        space_id="8609fdea87b44e2f8e0",
        identifiers="zqmgs2tmspguoqcxyahsya,R4VM29Oj0fVM2hhEmSKVM2hhezJTezJTKVM2hezJT2hezJ",
    )
    adapter = TypeAdapter(models.DeleteChatSpacesSpaceIdAdminsResponse)
    adapter.validate_python(response)
