"""File Generated by Sideko (sideko.dev)"""

import pytest
from zoom_team_chat import Client, AsyncClient
from os import getenv
from zoom_team_chat.types.im.user.me.chat.message import models
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_send_201_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(token=getenv("API_TOKEN"))
    response = client.im.user.me.chat.message.send(
        chat_user="jchill@example\.com", data={"message": "hello, world!"}
    )
    adapter = TypeAdapter(models.PostImUsersMeChatMessagesResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_send_201_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(token=getenv("API_TOKEN"))
    response = await client.im.user.me.chat.message.send(
        chat_user="jchill@example\.com", data={"message": "hello, world!"}
    )
    adapter = TypeAdapter(models.PostImUsersMeChatMessagesResponse)
    adapter.validate_python(response)
