"""File Generated by Sideko (sideko.dev)"""

import io
import typing
import typing_extensions
from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class GetReportChatSessionsResponseSessionsItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: typing.Optional[str] = _PydanticField(alias="id", default=None)
    last_message_sent_time: typing.Optional[str] = _PydanticField(
        alias="last_message_sent_time", default=None
    )
    name: typing.Optional[str] = _PydanticField(alias="name", default=None)
    type: typing.Optional[typing_extensions.Literal["Group", "1:1"]] = _PydanticField(
        alias="type", default=None
    )
    channel_id: typing.Optional[str] = _PydanticField(alias="channel_id", default=None)


class GetReportChatSessionsSessionIdResponseDeletedMessagesItemFilesItem(
    _PydanticBaseModel
):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    download_url: typing.Optional[str] = _PydanticField(
        alias="download_url", default=None
    )
    file_id: typing.Optional[str] = _PydanticField(alias="file_id", default=None)
    file_name: typing.Optional[str] = _PydanticField(alias="file_name", default=None)
    file_size: typing.Optional[int] = _PydanticField(alias="file_size", default=None)


class GetReportChatSessionsSessionIdResponseEditedMessagesItemFilesItem(
    _PydanticBaseModel
):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    download_url: typing.Optional[str] = _PydanticField(
        alias="download_url", default=None
    )
    file_id: typing.Optional[str] = _PydanticField(alias="file_id", default=None)
    file_name: typing.Optional[str] = _PydanticField(alias="file_name", default=None)
    file_size: typing.Optional[int] = _PydanticField(alias="file_size", default=None)


class GetReportChatSessionsSessionIdResponseMessagesItemFilesItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    download_url: typing.Optional[str] = _PydanticField(
        alias="download_url", default=None
    )
    file_id: typing.Optional[str] = _PydanticField(alias="file_id", default=None)
    file_name: typing.Optional[str] = _PydanticField(alias="file_name", default=None)
    file_size: typing.Optional[int] = _PydanticField(alias="file_size", default=None)


class GetReportChatSessionsSessionIdResponseMessagesItemBotMessage(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    is_markdown_support: typing.Optional[bool] = _PydanticField(
        alias="is_markdown_support", default=None
    )
    source: typing.Optional[str] = _PydanticField(alias="source", default=None)
    external_sender_email: typing.Optional[str] = _PydanticField(
        alias="external_sender_email", default=None
    )
    content: typing.Optional[typing.Dict[str, typing.Any]] = _PydanticField(
        alias="content", default=None
    )


class GetReportChatSessionsResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    from_field: typing.Optional[str] = _PydanticField(alias="from", default=None)
    next_page_token: typing.Optional[str] = _PydanticField(
        alias="next_page_token", default=None
    )
    page_size: typing.Optional[int] = _PydanticField(alias="page_size", default=None)
    sessions: typing.Optional[
        typing.List[GetReportChatSessionsResponseSessionsItem]
    ] = _PydanticField(alias="sessions", default=None)
    to: typing.Optional[str] = _PydanticField(alias="to", default=None)


class GetReportChatSessionsSessionIdResponseDeletedMessagesItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    date_time: typing.Optional[str] = _PydanticField(alias="date_time", default=None)
    files: typing.Optional[
        typing.List[GetReportChatSessionsSessionIdResponseDeletedMessagesItemFilesItem]
    ] = _PydanticField(alias="files", default=None)
    id: typing.Optional[str] = _PydanticField(alias="id", default=None)
    message: typing.Optional[str] = _PydanticField(alias="message", default=None)
    receiver: typing.Optional[str] = _PydanticField(alias="receiver", default=None)
    reply_main_message_id: typing.Optional[str] = _PydanticField(
        alias="reply_main_message_id", default=None
    )
    reply_main_message_timestamp: typing.Optional[int] = _PydanticField(
        alias="reply_main_message_timestamp", default=None
    )
    sender: typing.Optional[str] = _PydanticField(alias="sender", default=None)
    sender_member_id: typing.Optional[str] = _PydanticField(
        alias="sender_member_id", default=None
    )
    sender_display_name: typing.Optional[str] = _PydanticField(
        alias="sender_display_name", default=None
    )
    timestamp: typing.Optional[int] = _PydanticField(alias="timestamp", default=None)


class GetReportChatSessionsSessionIdResponseEditedMessagesItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    date_time: typing.Optional[str] = _PydanticField(alias="date_time", default=None)
    files: typing.Optional[
        typing.List[GetReportChatSessionsSessionIdResponseEditedMessagesItemFilesItem]
    ] = _PydanticField(alias="files", default=None)
    id: typing.Optional[str] = _PydanticField(alias="id", default=None)
    message: typing.Optional[str] = _PydanticField(alias="message", default=None)
    receiver: typing.Optional[str] = _PydanticField(alias="receiver", default=None)
    reply_main_message_id: typing.Optional[str] = _PydanticField(
        alias="reply_main_message_id", default=None
    )
    reply_main_message_timestamp: typing.Optional[int] = _PydanticField(
        alias="reply_main_message_timestamp", default=None
    )
    sender_member_id: typing.Optional[str] = _PydanticField(
        alias="sender_member_id", default=None
    )
    sender: typing.Optional[str] = _PydanticField(alias="sender", default=None)
    sender_display_name: typing.Optional[str] = _PydanticField(
        alias="sender_display_name", default=None
    )
    timestamp: typing.Optional[int] = _PydanticField(alias="timestamp", default=None)


class GetReportChatSessionsSessionIdResponseMessagesItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    date_time: typing.Optional[str] = _PydanticField(alias="date_time", default=None)
    files: typing.Optional[
        typing.List[GetReportChatSessionsSessionIdResponseMessagesItemFilesItem]
    ] = _PydanticField(alias="files", default=None)
    id: typing.Optional[str] = _PydanticField(alias="id", default=None)
    message: typing.Optional[str] = _PydanticField(alias="message", default=None)
    receiver: typing.Optional[str] = _PydanticField(alias="receiver", default=None)
    reply_main_message_id: typing.Optional[str] = _PydanticField(
        alias="reply_main_message_id", default=None
    )
    reply_main_message_timestamp: typing.Optional[int] = _PydanticField(
        alias="reply_main_message_timestamp", default=None
    )
    sender: typing.Optional[str] = _PydanticField(alias="sender", default=None)
    sender_member_id: typing.Optional[str] = _PydanticField(
        alias="sender_member_id", default=None
    )
    sender_display_name: typing.Optional[str] = _PydanticField(
        alias="sender_display_name", default=None
    )
    timestamp: typing.Optional[int] = _PydanticField(alias="timestamp", default=None)
    bot_message: typing.Optional[
        GetReportChatSessionsSessionIdResponseMessagesItemBotMessage
    ] = _PydanticField(alias="bot_message", default=None)


class GetReportChatSessionsSessionIdResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    deleted_messages: typing.Optional[
        typing.List[GetReportChatSessionsSessionIdResponseDeletedMessagesItem]
    ] = _PydanticField(alias="deleted_messages", default=None)
    edited_messages: typing.Optional[
        typing.List[GetReportChatSessionsSessionIdResponseEditedMessagesItem]
    ] = _PydanticField(alias="edited_messages", default=None)
    from_field: typing.Optional[str] = _PydanticField(alias="from", default=None)
    messages: typing.Optional[
        typing.List[GetReportChatSessionsSessionIdResponseMessagesItem]
    ] = _PydanticField(alias="messages", default=None)
    next_page_token: typing.Optional[str] = _PydanticField(
        alias="next_page_token", default=None
    )
    page_size: typing.Optional[int] = _PydanticField(alias="page_size", default=None)
    to: typing.Optional[str] = _PydanticField(alias="to", default=None)
