"""File Generated by Sideko (sideko.dev)"""

import io
import typing

from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class GetChatChannelsResponseChannelsItemChannelSettings(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    add_member_permissions: typing.Optional[int] = _PydanticField(
        alias="add_member_permissions", default=None
    )
    new_members_can_see_previous_messages_files: typing.Optional[bool] = _PydanticField(
        alias="new_members_can_see_previous_messages_files", default=None
    )
    posting_permissions: typing.Optional[int] = _PydanticField(
        alias="posting_permissions", default=None
    )
    mention_all_permissions: typing.Optional[int] = _PydanticField(
        alias="mention_all_permissions", default=None
    )
    allow_to_add_external_users: typing.Optional[int] = _PydanticField(
        alias="allow_to_add_external_users", default=None
    )


class GetChatChannelsChannelIdResponseChannelSettings(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    add_member_permissions: typing.Optional[int] = _PydanticField(
        alias="add_member_permissions", default=None
    )
    new_members_can_see_previous_messages_files: typing.Optional[bool] = _PydanticField(
        alias="new_members_can_see_previous_messages_files", default=None
    )
    posting_permissions: typing.Optional[int] = _PydanticField(
        alias="posting_permissions", default=None
    )
    mention_all_permissions: typing.Optional[int] = _PydanticField(
        alias="mention_all_permissions", default=None
    )
    allow_to_add_external_users: typing.Optional[int] = _PydanticField(
        alias="allow_to_add_external_users", default=None
    )


class PostChatChannelsSearchResponseChannelsItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: str = _PydanticField(alias="id")
    name: str = _PydanticField(alias="name")
    type: int = _PydanticField(alias="type")
    channel_url: str = _PydanticField(alias="channel_url")
    total_members: int = _PydanticField(alias="total_members")


class GetChatChannelsResponseChannelsItemUnion(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )


class GetChatChannelsChannelIdResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    channel_settings: typing.Optional[
        GetChatChannelsChannelIdResponseChannelSettings
    ] = _PydanticField(alias="channel_settings", default=None)
    id: typing.Optional[str] = _PydanticField(alias="id", default=None)
    jid: typing.Optional[str] = _PydanticField(alias="jid", default=None)
    name: typing.Optional[str] = _PydanticField(alias="name", default=None)
    type: typing.Optional[int] = _PydanticField(alias="type", default=None)
    channel_url: typing.Optional[str] = _PydanticField(
        alias="channel_url", default=None
    )


class PostChatChannelsSearchResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    channels: typing.List[PostChatChannelsSearchResponseChannelsItem] = _PydanticField(
        alias="channels"
    )
    next_page_token: typing.Optional[str] = _PydanticField(
        alias="next_page_token", default=None
    )
    page_size: int = _PydanticField(alias="page_size")


class GetChatChannelsResponseUnion(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )
