"""File Generated by Sideko (sideko.dev)"""

import pytest
from zoom_team_chat import Client, AsyncClient
from os import getenv
from pydantic import TypeAdapter
from zoom_team_chat.types.chat.file import models

# test sync & async methods (keep comment for code generation)


def test_get_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(token=getenv("API_TOKEN"))
    response = client.chat.file.get(file_id="LDG2jzoOS2aV4wkyLMaryg")
    adapter = TypeAdapter(models.GetChatFilesFileIdResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_get_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(token=getenv("API_TOKEN"))
    response = await client.chat.file.get(file_id="LDG2jzoOS2aV4wkyLMaryg")
    adapter = TypeAdapter(models.GetChatFilesFileIdResponse)
    adapter.validate_python(response)


def test_delete_204_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(token=getenv("API_TOKEN"))
    response = client.chat.file.delete(file_id="LDG2jzoOS2aV4wkyLMaryg")
    adapter = TypeAdapter(None)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_delete_204_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(token=getenv("API_TOKEN"))
    response = await client.chat.file.delete(file_id="LDG2jzoOS2aV4wkyLMaryg")
    adapter = TypeAdapter(None)
    adapter.validate_python(response)
