"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PatchChatInvitationsApprovalsAdminBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    response: typing_extensions.Required[typing_extensions.Literal["approve", "deny"]]
    invitation_ids: typing_extensions.Required[typing.List[str]]


class _SerializerPatchChatInvitationsApprovalsAdminBody(pydantic.BaseModel):
    """
    Serializer for PatchChatInvitationsApprovalsAdminBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    response: typing_extensions.Literal["approve", "deny"] = pydantic.Field(
        alias="response"
    )
    invitation_ids: typing.List[str] = pydantic.Field(alias="invitation_ids")
