"""File Generated by Sideko (sideko.dev)"""

import io
import typing

from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class PatchChatChannelsEventsResponseFailedChannelsItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    channel_id: typing.Optional[str] = _PydanticField(alias="channel_id", default=None)
    reason: typing.Optional[str] = _PydanticField(alias="reason", default=None)
    error_code: typing.Optional[str] = _PydanticField(alias="error_code", default=None)


class PatchChatChannelsEventsResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    failed_channels: typing.Optional[
        typing.List[PatchChatChannelsEventsResponseFailedChannelsItem]
    ] = _PydanticField(alias="failed_channels", default=None)
