"""File Generated by Sideko (sideko.dev)"""

import pytest
from zoom_team_chat import Client, AsyncClient
from os import getenv
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_migrate_204_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(token=getenv("API_TOKEN"))
    response = client.chat.migration.channel.member.migrate(
        channel_id="649ad5f12f804cfea7dd7b1c1bb4c337",
        data={"members": [{"identifier": "qwwHGx5jSU2E1X46SLfGoA", "role": "admin"}]},
    )
    adapter = TypeAdapter(None)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_migrate_204_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(token=getenv("API_TOKEN"))
    response = await client.chat.migration.channel.member.migrate(
        channel_id="649ad5f12f804cfea7dd7b1c1bb4c337",
        data={"members": [{"identifier": "qwwHGx5jSU2E1X46SLfGoA", "role": "admin"}]},
    )
    adapter = TypeAdapter(None)
    adapter.validate_python(response)
