"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PostImGroupsGroupIdMembersBodyMembersItem(typing_extensions.TypedDict):
    """
    No description specified
    """

    email: typing_extensions.NotRequired[str]
    id: typing_extensions.NotRequired[str]


class _SerializerPostImGroupsGroupIdMembersBodyMembersItem(pydantic.BaseModel):
    """
    Serializer for PostImGroupsGroupIdMembersBodyMembersItem handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    email: typing.Optional[str] = pydantic.Field(alias="email", default=None)
    id: typing.Optional[str] = pydantic.Field(alias="id", default=None)


class PostImGroupsGroupIdMembersBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    members: typing_extensions.NotRequired[
        typing.List[PostImGroupsGroupIdMembersBodyMembersItem]
    ]


class _SerializerPostImGroupsGroupIdMembersBody(pydantic.BaseModel):
    """
    Serializer for PostImGroupsGroupIdMembersBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    members: typing.Optional[
        typing.List[_SerializerPostImGroupsGroupIdMembersBodyMembersItem]
    ] = pydantic.Field(alias="members", default=None)
