"""File Generated by Sideko (sideko.dev)"""

import io
import typing

from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class GetChatChannelsChannelIdRetentionResponseCloudRetention(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    enable_custom_retention: bool = _PydanticField(alias="enable_custom_retention")
    retention_period: str = _PydanticField(alias="retention_period")


class GetChatChannelsChannelIdRetentionResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    channel_id: str = _PydanticField(alias="channel_id")
    cloud_retention: GetChatChannelsChannelIdRetentionResponseCloudRetention = (
        _PydanticField(alias="cloud_retention")
    )
