"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PatchChatInvitationsApprovalsBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    channel_id: typing_extensions.Required[str]
    invitee_identifier: typing_extensions.Required[str]
    response: typing_extensions.Required[
        typing_extensions.Literal["approve_invitation", "deny_invitation"]
    ]


class _SerializerPatchChatInvitationsApprovalsBody(pydantic.BaseModel):
    """
    Serializer for PatchChatInvitationsApprovalsBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    channel_id: str = pydantic.Field(alias="channel_id")
    invitee_identifier: str = pydantic.Field(alias="invitee_identifier")
    response: typing_extensions.Literal["approve_invitation", "deny_invitation"] = (
        pydantic.Field(alias="response")
    )
