"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PatchChatChannelMessageEventsBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    method: typing_extensions.Required[typing_extensions.Literal["pin", "unpin"]]
    message_id: typing_extensions.Required[str]
    channel_id: typing_extensions.Required[str]


class _SerializerPatchChatChannelMessageEventsBody(pydantic.BaseModel):
    """
    Serializer for PatchChatChannelMessageEventsBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    method: typing_extensions.Literal["pin", "unpin"] = pydantic.Field(alias="method")
    message_id: str = pydantic.Field(alias="message_id")
    channel_id: str = pydantic.Field(alias="channel_id")
