"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PostChatSpacesSpaceIdAdminsBodyMembersItem(typing_extensions.TypedDict):
    """
    The information about the user.
    """

    identifier: typing_extensions.Required[str]


class _SerializerPostChatSpacesSpaceIdAdminsBodyMembersItem(pydantic.BaseModel):
    """
    Serializer for PostChatSpacesSpaceIdAdminsBodyMembersItem handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    identifier: str = pydantic.Field(alias="identifier")


class PostChatSpacesSpaceIdAdminsBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    members: typing_extensions.Required[
        typing.List[PostChatSpacesSpaceIdAdminsBodyMembersItem]
    ]


class _SerializerPostChatSpacesSpaceIdAdminsBody(pydantic.BaseModel):
    """
    Serializer for PostChatSpacesSpaceIdAdminsBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    members: typing.List[_SerializerPostChatSpacesSpaceIdAdminsBodyMembersItem] = (
        pydantic.Field(alias="members")
    )
