"""File Generated by Sideko (sideko.dev)"""

import pytest
from zoom_team_chat import AsyncClient, Client
from os import getenv
from zoom_team_chat.types.chat.migration.user.channel import models
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_migrate_201_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(token=getenv("API_TOKEN"))
    response = client.chat.migration.user.channel.migrate(
        identifier="649ad5f12f804cfea7dd7b1c1bb4c337",
        data={
            "members": [{"identifier": "xyzHGx5jSU2E1X46SLfBbq", "role": "admin"}],
            "type": 2,
            "name": "Developers",
            "created_time": "2023\-02\-13T15:23:14\.541Z",
        },
    )
    adapter = TypeAdapter(models.PostChatMigrationUsersIdentifierChannelsResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_migrate_201_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(token=getenv("API_TOKEN"))
    response = await client.chat.migration.user.channel.migrate(
        identifier="649ad5f12f804cfea7dd7b1c1bb4c337",
        data={
            "members": [{"identifier": "xyzHGx5jSU2E1X46SLfBbq", "role": "admin"}],
            "type": 2,
            "name": "Developers",
            "created_time": "2023\-02\-13T15:23:14\.541Z",
        },
    )
    adapter = TypeAdapter(models.PostChatMigrationUsersIdentifierChannelsResponse)
    adapter.validate_python(response)
