"""File Generated by Sideko (sideko.dev)"""

import pytest
from zoom_team_chat import AsyncClient, Client
from os import getenv
from zoom_team_chat.types.contact import models
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_search_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(token=getenv("API_TOKEN"))
    response = client.contact.search(
        search_key="jchill@example\.com",
        contact_types=1,
        next_page_token="R4aF9Oj0fVM2hhezJTEmSKaBSkfesDwGy42",
        page_size=20,
        query_presence_status=True,
        user_status="active",
    )
    adapter = TypeAdapter(models.GetContactsResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_search_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(token=getenv("API_TOKEN"))
    response = await client.contact.search(
        search_key="jchill@example\.com",
        contact_types=1,
        next_page_token="R4aF9Oj0fVM2hhezJTEmSKaBSkfesDwGy42",
        page_size=20,
        query_presence_status=True,
        user_status="active",
    )
    adapter = TypeAdapter(models.GetContactsResponse)
    adapter.validate_python(response)
