"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PostChatMessagesMessageIdReminderBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    to_contact: typing_extensions.NotRequired[str]
    to_channel: typing_extensions.NotRequired[str]
    remind_time: typing_extensions.NotRequired[str]
    delay_seconds: typing_extensions.NotRequired[int]
    reminder_note: typing_extensions.NotRequired[str]


class _SerializerPostChatMessagesMessageIdReminderBody(pydantic.BaseModel):
    """
    Serializer for PostChatMessagesMessageIdReminderBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    to_contact: typing.Optional[str] = pydantic.Field(alias="to_contact", default=None)
    to_channel: typing.Optional[str] = pydantic.Field(alias="to_channel", default=None)
    remind_time: typing.Optional[str] = pydantic.Field(
        alias="remind_time", default=None
    )
    delay_seconds: typing.Optional[int] = pydantic.Field(
        alias="delay_seconds", default=None
    )
    reminder_note: typing.Optional[str] = pydantic.Field(
        alias="reminder_note", default=None
    )
