"""File Generated by Sideko (sideko.dev)"""

import io
import typing
import typing_extensions
from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class GetChatUsersMeContactsResponseContactsItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    email: typing.Optional[str] = _PydanticField(alias="email", default=None)
    first_name: typing.Optional[str] = _PydanticField(alias="first_name", default=None)
    id: typing.Optional[str] = _PydanticField(alias="id", default=None)
    member_id: typing.Optional[str] = _PydanticField(alias="member_id", default=None)
    last_name: typing.Optional[str] = _PydanticField(alias="last_name", default=None)


class GetChatUsersMeContactsIdentifierResponsePhoneNumbersItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    code: typing.Optional[str] = _PydanticField(alias="code", default=None)
    country: typing.Optional[str] = _PydanticField(alias="country", default=None)
    label: typing.Optional[
        typing_extensions.Literal["Mobile", "Office", "Home", "Fax"]
    ] = _PydanticField(alias="label", default=None)
    number: typing.Optional[str] = _PydanticField(alias="number", default=None)
    verified: typing.Optional[bool] = _PydanticField(alias="verified", default=None)


class GetChatUsersMeContactsResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    contacts: typing.Optional[
        typing.List[GetChatUsersMeContactsResponseContactsItem]
    ] = _PydanticField(alias="contacts", default=None)
    next_page_token: typing.Optional[str] = _PydanticField(
        alias="next_page_token", default=None
    )
    page_size: typing.Optional[int] = _PydanticField(alias="page_size", default=None)


class GetChatUsersMeContactsIdentifierResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    direct_numbers: typing.Optional[typing.List[str]] = _PydanticField(
        alias="direct_numbers", default=None
    )
    email: typing.Optional[str] = _PydanticField(alias="email", default=None)
    extension_number: typing.Optional[str] = _PydanticField(
        alias="extension_number", default=None
    )
    first_name: typing.Optional[str] = _PydanticField(alias="first_name", default=None)
    id: typing.Optional[str] = _PydanticField(alias="id", default=None)
    member_id: typing.Optional[str] = _PydanticField(alias="member_id", default=None)
    last_name: typing.Optional[str] = _PydanticField(alias="last_name", default=None)
    phone_number: typing.Optional[str] = _PydanticField(
        alias="phone_number", default=None
    )
    phone_numbers: typing.Optional[
        typing.List[GetChatUsersMeContactsIdentifierResponsePhoneNumbersItem]
    ] = _PydanticField(alias="phone_numbers", default=None)
    presence_status: typing.Optional[
        typing_extensions.Literal[
            "Do_Not_Disturb",
            "Away",
            "Available",
            "Offline",
            "In_A_Meeting",
            "In_A_Call",
            "In_A_Calendar_Event",
            "Presenting",
            "Out_of_Office",
            "Busy",
        ]
    ] = _PydanticField(alias="presence_status", default=None)
