"""File Generated by Sideko (sideko.dev)"""

import io
import typing
import typing_extensions
from pydantic import (
    BaseModel as _PydanticBaseModel,
    Field as _PydanticField,
    ConfigDict as _PydanticConfigDict,
)

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class GetChatInvitationsResponseInvitationsItemInvitersItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    display_name: str = _PydanticField(alias="display_name")


class GetChatInvitationsInviteLinkResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    invite_link: str = _PydanticField(alias="invite_link")


class PostChatInvitationsJoinResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    status: typing_extensions.Literal["joined", "approval_pending"] = _PydanticField(
        alias="status"
    )
    channel_id: typing.Optional[str] = _PydanticField(alias="channel_id", default=None)


class GetChatInvitationsResponseInvitationsItem(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    channel_id: str = _PydanticField(alias="channel_id")
    channel_name: str = _PydanticField(alias="channel_name")
    inviters: typing.List[GetChatInvitationsResponseInvitationsItemInvitersItem] = (
        _PydanticField(alias="inviters")
    )


class GetChatInvitationsResponse(_PydanticBaseModel):
    model_config = _PydanticConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    invitations: typing.List[GetChatInvitationsResponseInvitationsItem] = (
        _PydanticField(alias="invitations")
    )
    next_page_token: typing.Optional[str] = _PydanticField(
        alias="next_page_token", default=None
    )
    page_size: int = _PydanticField(alias="page_size")
