"""File Generated by Sideko (sideko.dev)"""

import pytest
from zoom_team_chat import Client, AsyncClient
from os import getenv
from zoom_team_chat.types.chat.user.me.contact import models
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_get_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(token=getenv("API_TOKEN"))
    response = client.chat.user.me.contact.get(
        identifier="jchill@example\.com", query_presence_status=True
    )
    adapter = TypeAdapter(models.GetChatUsersMeContactsIdentifierResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_get_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(token=getenv("API_TOKEN"))
    response = await client.chat.user.me.contact.get(
        identifier="jchill@example\.com", query_presence_status=True
    )
    adapter = TypeAdapter(models.GetChatUsersMeContactsIdentifierResponse)
    adapter.validate_python(response)


def test_list_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(token=getenv("API_TOKEN"))
    response = client.chat.user.me.contact.list(
        next_page_token="R4aF9Oj0fVM2hhezJTEmSKaBSkfesDwGy42",
        page_size=10,
        type="company",
    )
    adapter = TypeAdapter(models.GetChatUsersMeContactsResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_list_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(token=getenv("API_TOKEN"))
    response = await client.chat.user.me.contact.list(
        next_page_token="R4aF9Oj0fVM2hhezJTEmSKaBSkfesDwGy42",
        page_size=10,
        type="company",
    )
    adapter = TypeAdapter(models.GetChatUsersMeContactsResponse)
    adapter.validate_python(response)
