"""File Generated by Sideko (sideko.dev)"""

from zoom_team_chat.utils.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from zoom_team_chat.resources.chat.migration.channel.member import (
    AsyncMemberClient,
    MemberClient,
)


class ChannelClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper
        # register sync resources (keep comment for code generation)
        self.member = MemberClient(client_wrapper=self._client_wrapper)

    # register sync api methods (keep comment for code generation)


class AsyncChannelClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper
        # register async resources (keep comment for code generation)
        self.member = AsyncMemberClient(client_wrapper=self._client_wrapper)

    # register async api methods (keep comment for code generation)
